### ISSUE TITLE
[Space] - Airdrop implementation

### ISSUE THREAD

**Issue by devformatters** [thematters/airdrops#1]
- [x] Snapshot script
- [x] Merkle root generator 
- [x] Claiming interface (web)
- [x] Data feed for client to query a address's claimable tokens (items)
- [x] Contract
  - ~~root can be updated~~
  - owner can withdraw unclaim tokens
  - has an expiration date
  - ~~address can claim multiple times if still has unclaim tokens~~

**Comment by robertu7** [comment]
## Thrid-party Sources

### POAP

https://thegraph.com/hosted-service/subgraph/poap-xyz/poap-xdai

```gql
query {
  tokens(
    where: {
      event: "31209"
      owner_not: "0x0000000000000000000000000000000000000000"
    }
    first: 1000
    skip: 0
  ) {
    transferCount
    created
    owner {
      id
    }
  }
}

```

### NFT on Ethereum and Polygon
https://github.com/thematters/traveloggers-contracts/blob/develop/scripts/tasks/getOwners.ts

### The Space Participants on Polygon Mumbai
