### ISSUE TITLE
[Space] - Fairdrop implementation: contract & server

### ISSUE THREAD

**Issue by devformatters** [thematters/airdrops#4]
tasks
- Twitter / Discord API
- Snapshot or Verification
- Claiming website
- Contract

[API Specs](https://github.com/thematters/airdrops/issues/4)

**Comment by robertu7** [comment]
## Fairdrop API Specs

### Get Nonce
**URL**: `/api/fairdrop/nonce`

**Method**: `GET`

**Query Parameters**
| Name | Type | Description |
|-------------- |-------------- |-------------- |
| `account` | `String` | **Required**. ETH address to claim the fairdrop. |

**Response Status**: `200 OK`

**Response Body**
| Name | Type | Description |
|-------------- |-------------- |-------------- |
| `account` | `String` | ETH address to claim the fairdrop. |
| `nonce` | `String` | Unique ID for address (claimer sign message) and social (e.g. via tweet) verifications. |
| `exipredAt` | `String` | Timestamp in ISO 8601 format. Expiration date to claim the fairdrop. |
| `signerSig` | `String` | A signature signed by backend signer. |

**Error Codes**
| Error Code | Status Code | Description |
|-------------- |-------------- |-------------- |
| `INVALID_ACCOUNT` | `400` | Invalid account.  |
| `INTERNAL_ERROR` | `500` | Internal server error. | 

### Confirm Claim

**URL**: `/api/fairdrop/confirm`

**Method**: `POST`

**Request Parameters**
| Name | Type | Description |
|-------------- |-------------- |-------------- |
| `account` | `String` | **Required**. ETH address to claim the fairdrop. |
| `nonce ` | `String` | **Required**. Unique ID from **Get Nonce** API. |
| `expiredAt ` | `String` | **Required**. Expiration date from **Get Nonce** API. |
| `signerSig ` | `String` | **Required**. Signer's Signature from **Get Nonce** API. |
| `claimerSig ` | `String` | **Required**. A signature signed by claimer [1] |
| `tweetURL ` | `String` | **Required**. Tweet link for social verification, tweet content must contains `nonce`. |

**Response Status**: `200 OK`

**Response Body**
| Name | Type | Description |
|-------------- |-------------- |-------------- |
| `account` | `String` | ETH address to claim the fairdrop. |
| `userId` | `String` | Hashed User ID to claim the fairdrop. |
| `nonce ` | `String` | **Required**. Unique ID from **Get Nonce** API. |
| `expiredAt` | `String` | Same value as from **Get Nonce** API. |
| `sigV` | `String` | Signature Field `v`. |
| `sigR` | `String` | Signature Field `r`. |
| `sigS` | `String` | Signature Field `s`. |

**Error Codes**
| Error Code | Status Code | Description |
|-------------- |-------------- |-------------- |
| `INVALID_NONCE` | `400` | Invalid `nonce`.  |
| `INVALID_ACCOUNT` | `400` | Invalid account.  |
| `INVALID_SIGNATURE` | `400` | Invalid signature.  |
| `INVALID_TWEET_URL` | `400` | Invalid tweet url.  |
| `CLAIM_EXPIRED` | `400` | `exipredAt` is less than now. | 
| `INTERNAL_ERROR` | `500` | Internal server error. | 

---
**[1]** Message template:
```
I am signing this message to prove the ownership of this address.

Nonce: XXX
ExpiredAt: XXX
```

## Fairdrop Contract ABI Specs

### Contract Addresses
| Name | Type | Description |
|-------------- |-------------- |-------------- |
| `Fairdrop.sol` | Polygon Mumbai | [`0x687daf30E1A1b6485e448567c0d6221B58d5c7e0`](https://mumbai.polygonscan.com/address/0x687daf30e1a1b6485e448567c0d6221b58d5c7e0) |
| `Fairdrop.sol` | Polygon Mainnet | `0x...` |

### Interfaces
```solidity
[
  'constructor(address token_, address signer_, address owner_, uint256 amountPerAddress_)',
  'error AddressAlreadyClaimed(address account)',
  'error ClaimExpired()',
  'error InvalidSignature()',
  'error TransferFailed(address account, uint256 amount)',
  'error UserIdAlreadyClaimed(bytes32 userId)',
  'event AmountChanged(uint256 amount)',
  'event Claimed(address indexed account, bytes32 indexed userId, uint256 amount)',
  'event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)',
  'event SignerChanged(address indexed signer)',
  'event Swept(address indexed target, uint256 amount)',
  'function addressClaimed(address) view returns (bool)',
  'function amountPerAddress() view returns (uint256)',
  'function claim(address account_, bytes32 userId_, string nonce_, uint256 expiredAt_, uint8 v_, bytes32 r_, bytes32 s_) returns (bool success)',
  'function owner() view returns (address)',
  'function renounceOwnership()',
  'function setAmountPerAddress(uint256 amount_)',
  'function setSigner(address signer_)',
  'function signer() view returns (address)',
  'function sweep(address target_)',
  'function sweepToOwner()',
  'function token() view returns (address)',
  'function transferOwnership(address newOwner)',
  'function userIdClaimed(bytes32) view returns (bool)'
]
```

| Name | Description |
|-------------- |-------------- |
| `function amountPerAddress() view returns (uint256)` | Numbers of tokens user can be claimed. |
| `function addressClaimed(address) view returns (bool)` | `mapping(address => bool)`. Is current address already claimed? |
| `function userIdClaimed(bytes32) view returns (bool)` | `mapping(bytes32 => bool)`. Is current social user id already claimed? |
| `function claim(address account_, bytes32 userId_, string nonce_, uint256 expiredAt_, uint8 v_, bytes32 r_, bytes32 s_) returns (bool success)` | Claim a fairdrop.  |
